name: C/C++ CI

on:
  #push:
    #branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make -j`nproc`
    - name: upload-build-artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output-gcc
        path: bin
    - name: make tests
      run: make tests > test-output.txt
      continue-on-error: true
    - name: upload-build-artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-output-gcc
        path: test-output.txt

  build-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: CC=clang CXX=clang++ make -j`nproc`
    - name: upload-build-artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output-clang
        path: bin
    - name: make tests
      run: make tests > test-output.txt
      continue-on-error: true
    - name: upload-build-artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-output-clang
        path: test-output.txt

    
